
env:
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=7.10.1 CABALVER=1.22
   - env: GHCVER=head CABALVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - cabal --version

install:
    - sudo add-apt-repository -y ppa:yandex-sysmon/zookeeper-3.4
    - sudo apt-get update
    - sudo apt-get install -y libzookeeper-mt-dev zookeeperd
    - cabal update
    - cabal install -j hspec cabal-meta cabal-src
    - cabal-meta install -j --only-dep --force-reinstalls
    - cabal-meta install -j

script:
    - mega-sdist --test
    - cd persistent-test
    - cabal install -j --only-dep  --enable-tests --force-reinstalls
    - "cabal configure -fmysql --enable-tests      && cabal test"
    - "cabal configure -fpostgresql --enable-tests && cabal test"
    - "cabal configure -fmongodb --enable-tests    && cabal test"
    - "cabal configure -fzookeeper --enable-tests  && cabal test"

addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database persistent;' -U postgres
  - mysql -e 'create database persistent;'
  - sudo mkdir -p /var/log/zookeeper
  - sudo chmod -R 777 /var/log/zookeeper
  - sudo chmod 666 /etc/zookeeper/conf/zoo.cfg
  - echo maxClientCnxns=128 >> /etc/zookeeper/conf/zoo.cfg
  - sudo service zookeeper restart
  - sleep 10
  - /usr/share/zookeeper/bin/zkCli.sh create /persistent null

services:
    - mysql
    - mongodb
