resolver: nightly-2021-05-20
packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
    # - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
  - lift-type-0.1.0.0
  - dhall-1.37.1
  - generic-lens-2.0.0.0

